config/routes.rb
Rails.application.routes.draw do
  get 'test_page/index'

  resources :candidates

  # get  '/candidate',    to: 'candidates#index'
  # get  '/new',  to: 'candidates#new'
  # get  '/edit',    to: 'candidates#edit'
  # get  '/delete',    to: 'candidates#delete'
  # post '/create',  to: 'candidates#create'
  # root 'candidates#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'candidates#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }
  validates :phone, presence: true
  validates :address, presence: true, length: { maximum: 255 }
  validates :position, presence: true
  validates :pre_salary, presence: true
  validates :expect_salary, presence: true
  validates :source, presence: true
  validates :source_detail, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]

  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.all
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
  end

  # GET /candidates/1/edit
  def edit
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(candidate_params)
    respond_to do |format|
      if @candidate.save
        format.html { render :show }
      else
        format.html { render :new }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidates/1
  # PATCH/PUT /candidates/1.json
  def update
    respond_to do |format|
      if @candidate.update(candidate_params)
        format.json { render :show, status: :ok, location: @candidate }
      else
        format.html { render :edit }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate.destroy
    respond_to do |format|
    format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_params
      params.fetch(:candidate, {})
      params.require(:candidate).permit(:name, :email, :phone, 
      :address, :position, :pre_salary, :expect_salary ,:source ,:source_detail)
    end
end

app/controllers/test_page_controller.rb
class TestPageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/test_page_helper.rb
module TestPageHelper
end

app/views/candidates/_form.html.erb
<%= form_for(candidate) do |f| %>
  <% if candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% candidate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
      <p class="form-inline">  
      <%= f.label :name %>
      <a id="add_form_50"><%= f.text_field :name, {class: 'form-control' , :style => "min-width: 340px;"} %></a>
      </p>
      <p class="form-inline"> 
      <%= f.label :email %>
      <a id="add_form_50"><%= f.email_field :email, {class: 'form-control' , :style => "min-width: 340px;"} %></a>
      </p>
      <p class="form-inline"> 
      <%= f.label :phone %>
      <a style="margin-left: 45px;"><%= f.number_field :phone, {class: 'form-control' , :style => "min-width: 340px;"} %></a>
      </p>
      <p class="form-inline"> 
      <%= f.label :address %>
      <a id="add_form_30"><%= f.text_area :address, {class: 'form-control' , :style => "min-width: 340px;"} %></a>
      </p>
      <p class="form-inline"> 
      <%= f.label :position %>
      <a id="add_form_30"><%= f.select(:position, options_for_select([['1', 'RING'], ['2', 'NINE']]), {}, {class: "form-control" , :style => "min-width: 340px;"}) %></a>
      </p>
      <p class="form-inline"> 
      <%= f.label :'previous Salary' %>
      <a id="add_form_30"><%= f.number_field :pre_salary, {class: 'form-control' , :style => "min-width: 290px;"} %></a>
      </p>
      <p class="form-inline"> 
      <%= f.label :'expected Salary' %>
      <a id="add_form_30"><%= f.number_field :expect_salary, {class: 'form-control' , :style => "min-width: 290px;"} %></a>
      </p>
      <p class="form-inline">
        <%= f.label :'source' %>
            <a id="add_form_30"><%= f.select(:source, options_for_select([['1', 'RING'], ['2', 'NINE']]), {},  {class: "form-control" , :style => "min-width: 150px;"}) %></a> / 
            <%= f.text_field :source_detail, class: 'form-control' %>
      </p>

      <div style="margin-top: 10px;">
        <%= f.submit "Add new candidate", class: "btn btn-success" %>
      <%= link_to 'Back', candidates_path , class: "btn btn-primary" %>
      </div>

  </div>
<% end %>

app/views/candidates/_show.html.erb
<%= form_for(candidate) do |f| %>

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Candidate</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <!-- <link href="test.css" rel="stylesheet"> -->

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
  </head>

  <body>

      <div class="container">
      <div class="row" align="center">
        <div class="col-sm-2"  align="center" style="width: 185px; padding: 5px;">
        	<div><img src="/images/rss.jpg" alt="rss feed" height="150px" width="150px" ></div>
        	<div>ID : <%= @candidate.id %></div>
        </div>
        <div class="col-sm-2"  align="center" style="width: 185px; padding: 24px;">
      <p><%= f.submit "Submit", { class: "btn btn-success" , :style => "min-width: 100px;"} %></p>
			<p><%= link_to 'Back', candidates_path , {class: "btn btn-primary" , :style => "min-width: 100px;"} %></p>
			<p><%= link_to 'Delete', candidate, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-danger", :style => "min-width: 100px;" %></p>
        </div>
        <div class="col-sm-4"  style="width: 325px; padding: 19px;">
        	<p>

        <p class="form-inline">
            <label for="test"> Test Score : </label>
              <input type="text" class="form-control" aria-label="..." placeholder="general" style="width:90px">
              <input type="text" class="form-control" aria-label="..." placeholder="technical" style="width:90px">
        </p>

			</p>
			<p>
			</p>
			<p align="center">
			<button type="button" class="btn btn-default">Resume</button>
			</p>
        </div>
        <div class="col-sm-4" style="width: 372px; padding: 18px;">
        	<p>
        		<div class="form-inline" >
        			<label for="state"> Current state : </label>
  					<select class="form-control" id="sel1" style="width:200px" name="state">
    					<option>1</option>
    					<option>2</option>
    					<option>3</option>
    					<option>4</option>
  					</select>
				</div>
			</p>
			<p>
        		<div class="form-inline" >
        			<label for="status"> Current status: </label>
  					<select class="form-control" id="sel1" style="width:200px" name="status">
  						<option>-</option>
    					<option>Complete</option>
    					<option>In Process</option>
    					<option>Reject</option>
  					</select>
				</div>
			</p>
			<p>
        	<div class="progress" style="height: 25px;" >
  				<div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
    					60%
  				</div>
			</div>
        	</p>
        </div>
        </div>
    <!-- </div> -->
      <!-- Example row of columns -->
      <div class="row" >
        <div class="col-md-6" align="left"  style="width: 550px; padding: 19px;">
      <p class="form-inline">  
      <%= f.label :name %>
      <a id="add_form_50"><%= f.text_field :name, {class: 'form-control' , :style => "min-width: 340px;"} %></a>
      </p>
      <p class="form-inline"> 
      <%= f.label :email %>
      <a id="add_form_50"><%= f.email_field :email, {class: 'form-control' , :style => "min-width: 340px;"} %></a>
      </p>
      <p class="form-inline"> 
      <%= f.label :phone %>
      <a style="margin-left: 45px;"><%= f.number_field :phone, {class: 'form-control' , :style => "min-width: 340px;"} %></a>
      </p>
      <p class="form-inline"> 
      <%= f.label :address %>
      <a id="add_form_30"><%= f.text_area :address, {class: 'form-control' , :style => "min-width: 340px;"} %></a>
      </p>
      <p class="form-inline"> 
      <%= f.label :position %>
      <a id="add_form_30"><%= f.select(:position, options_for_select([['1', 'RING'], ['2', 'NINE']]), {}, {class: "form-control" , :style => "min-width: 340px;"}) %></a>
      </p>
      <p class="form-inline"> 
      <%= f.label :'previous Salary' %>
      <a id="add_form_30"><%= f.number_field :pre_salary, {class: 'form-control' , :style => "min-width: 290px;"} %></a>
      </p>
      <p class="form-inline"> 
      <%= f.label :'expected Salary' %>
      <a id="add_form_30"><%= f.number_field :expect_salary, {class: 'form-control' , :style => "min-width: 290px;"} %></a>
      </p>
      <p class="form-inline">
        <%= f.label :'source' %>
            <a id="add_form_30"><%= f.select(:source, options_for_select([['1', 'RING'], ['2', 'NINE']]), {},  {class: "form-control" , :style => "min-width: 150px;"}) %></a> / 
            <%= f.text_field :source_detail, class: 'form-control' %>
      </p>
       </div>
        <div class="col-md-6">

          <p>----COMENT FROM STAFFS----</p>

       </div>
      </div>
    </div><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

<% end %>

app/views/candidates/edit.html.erb
<h1>Editing Candidate</h1>

<%= render 'form', candidate: @candidate %>

app/views/candidates/index.html.erb
<h1>Candidates List</h1>

<%= link_to 'New Candidate', new_candidate_path , class: "btn btn-default" %>

<table class="table" style="margin-top: 30px">
  <thead>
    <tr>
        <th>Name</th>
        <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= link_to candidate.name, edit_candidate_path(candidate) %></td>
        <td><%= candidate.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/candidates/new.html.erb
<h1>New Candidate</h1>

<%= render 'form', candidate: @candidate %>

app/views/candidates/show.html.erb
<%= render 'show', candidate: @candidate %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  </small>
  <nav>
    <ul>
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "ARMS", root_path, id: "logo" %>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container" >
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
<!--           <a class="navbar-brand" href="#">Candidates</a> -->
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <!-- <li class="active"><a href="#">Home</a></li> -->
        <li><%= link_to "Candidate",    candidates_path %></li>
        <li><%= link_to "Staff",    '#' %></li>
        <li><%= link_to "Canlendar", '#' %></li>
        <li><%= link_to "Statistic", '#' %></li>
          </ul>
          <ul class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Username" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-default">Sign in</button>
          </ul>

        </div><!--/.nav-collapse -->
      </div>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AAAA</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/applicationORIGINAL.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Final</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/test_page/index.html.erb
<table class="table">
    <thead>
      <tr>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>John</td>
        <td>Doe</td>
        <td>john@example.com</td>
      </tr>
      <tr>
        <td>Mary</td>
        <td>Moe</td>
        <td>mary@example.com</td>
      </tr>
      <tr>
        <td>July</td>
        <td>Dooley</td>
        <td>july@example.com</td>
      </tr>
    </tbody>
</table>